[package]
name="powertoys-launcher"
version.workspace=true
edition.workspace=true
license.workspace=true
[[bin]]
name="powertoys-launcher"
path="src/main.rs"
[dependencies]
anyhow.workspace=true
clap.workspace=true
tokio.workspace=true
powertoys-core={path="../../crates/core"}
powertoys-ipc={path="../../crates/ipc"}
